openapi: 3.0.1
info:
  title: Quiz API
  description: Api for Quiz application
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Generated server url
paths:
  /api/questions/add:
    post:
      tags:
        - question-controller
      operationId: addQuestion
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QuestionDoc'
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/QuestionDoc'
  /api/questions:
    get:
      tags:
        - question-controller
      operationId: getQuestions
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/QuestionDoc'
  /api/questions/{id}:
    get:
      tags:
        - question-controller
      operationId: getQuestion
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/QuestionDoc'
components:
  schemas:
    AnswerDoc:
      type: object
      properties:
        content:
          type: string
    QuestionDoc:
      type: object
      properties:
        id:
          type: string
        content:
          type: string
        answers:
          type: array
          items:
            $ref: '#/components/schemas/AnswerDoc'
